#!/usr/bin/env python3
"""
Plot Performance from CSV Files

This script loads performance data from CSV files generated by PerformanceMonitor
and creates publication-quality plots.

Usage:
    python scripts/plot_from_csv.py --input results/ --output plots/
"""

import argparse
import pandas as pd
import numpy as np
from pathlib import Path
import sys
import glob

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.plot_performance import PerformancePlotter


def find_latest_csv_files(directory: str, prefix: str = "performance") -> dict:
    """
    Find the latest CSV files in a directory.
    
    Args:
        directory: Directory to search
        prefix: Filename prefix
        
    Returns:
        dict: Mapping of metric type to filepath
    """
    files = {}
    
    # Search for each metric type
    metric_types = ['latency', 'message_success', 'ambulance_travel',
                   'lane_clearance', 'speed_variance']
    
    for metric in metric_types:
        pattern = f"{directory}/{prefix}_{metric}_*.csv"
        matches = glob.glob(pattern)
        
        if matches:
            # Get the most recent file
            latest = max(matches, key=lambda x: Path(x).stat().st_mtime)
            files[metric] = latest
    
    return files


def plot_latency_from_csv(csv_file: str, plotter: PerformancePlotter):
    """Plot latency vs density from CSV."""
    df = pd.read_csv(csv_file)
    
    if df.empty:
        print(f"Warning: {csv_file} is empty")
        return
    
    # Group by distance bins to simulate density
    df['distance_bin'] = pd.cut(df['distance'], bins=10)
    grouped = df.groupby('distance_bin')['latency_ms'].agg(['mean', 'std', 'count'])
    
    # Use count as proxy for density
    densities = grouped['count'].tolist()
    latencies = grouped['mean'].tolist()
    latency_std = grouped['std'].fillna(0).tolist()
    
    # Group by message type
    slice_types = {}
    for msg_type in df['message_type'].unique():
        type_df = df[df['message_type'] == msg_type]
        type_df['distance_bin'] = pd.cut(type_df['distance'], bins=10)
        type_grouped = type_df.groupby('distance_bin')['latency_ms'].mean()
        
        slice_types[msg_type] = (
            type_grouped.index.categories.mid.tolist()[:len(type_grouped)],
            type_grouped.tolist()
        )
    
    plotter.plot_latency_vs_density(
        densities, latencies, latency_std,
        filename="latency_from_csv.png"
    )
    print("✓ Generated latency plot from CSV")


def plot_reliability_from_csv(csv_file: str, plotter: PerformancePlotter):
    """Plot reliability vs distance from CSV."""
    df = pd.read_csv(csv_file)
    
    if df.empty:
        print(f"Warning: {csv_file} is empty")
        return
    
    # Group by distance bins
    df['distance_bin'] = pd.cut(df['distance'], bins=15)
    grouped = df.groupby('distance_bin').agg({
        'success': 'mean',  # Success rate
        'distance': 'mean'
    }).sort_values('distance')
    
    distances = grouped['distance'].tolist()
    reliability = grouped['success'].tolist()
    
    # Group by message type
    slice_types = {}
    for msg_type in df['message_type'].unique():
        type_df = df[df['message_type'] == msg_type]
        type_df['distance_bin'] = pd.cut(type_df['distance'], bins=15)
        type_grouped = type_df.groupby('distance_bin').agg({
            'success': 'mean',
            'distance': 'mean'
        }).sort_values('distance')
        
        slice_types[msg_type] = (
            type_grouped['distance'].tolist(),
            type_grouped['success'].tolist()
        )
    
    plotter.plot_reliability_vs_distance(
        distances, reliability, slice_types,
        filename="reliability_from_csv.png"
    )
    print("✓ Generated reliability plot from CSV")


def plot_ambulance_speed_from_csv(csv_file: str, plotter: PerformancePlotter):
    """Plot ambulance speed from CSV."""
    df = pd.read_csv(csv_file)
    
    if df.empty:
        print(f"Warning: {csv_file} is empty")
        return
    
    # For each ambulance journey
    for idx, row in df.iterrows():
        # Generate time series from start to end
        duration = row['travel_time']
        num_points = int(duration) + 1
        
        timestamps = np.linspace(row['start_time'], row['end_time'], num_points)
        
        # Simulate speed profile based on average speed and variance
        avg_speed = row['average_speed']
        std_dev = row['speed_std_dev']
        
        speeds = np.random.normal(avg_speed, std_dev, num_points)
        speeds = np.clip(speeds, 0, avg_speed * 1.5)  # Reasonable bounds
        
        events = {
            'Journey Start': row['start_time'],
            'Journey End': row['end_time']
        }
        
        plotter.plot_ambulance_speed_over_time(
            timestamps.tolist(), speeds.tolist(),
            target_speed=avg_speed, events=events,
            filename=f"ambulance_speed_{row['vehicle_id']}_from_csv.png"
        )
        print(f"✓ Generated speed plot for {row['vehicle_id']}")


def plot_lane_clearance_from_csv(csv_file: str, plotter: PerformancePlotter):
    """Plot lane clearance times from CSV."""
    df = pd.read_csv(csv_file)
    
    if df.empty:
        print(f"Warning: {csv_file} is empty")
        return
    
    clearance_times = df['clearance_time'].tolist()
    action_types = df['action_type'].tolist() if 'action_type' in df.columns else None
    vehicle_ids = df['vehicle_id'].tolist() if 'vehicle_id' in df.columns else None
    
    plotter.plot_lane_clearance_time(
        clearance_times, action_types, vehicle_ids,
        filename="lane_clearance_from_csv.png"
    )
    print("✓ Generated lane clearance plot from CSV")


def plot_speed_variance_from_csv(csv_file: str, plotter: PerformancePlotter):
    """Plot speed variance comparison from CSV."""
    df = pd.read_csv(csv_file)
    
    if df.empty:
        print(f"Warning: {csv_file} is empty")
        return
    
    # Create comparison plot
    import matplotlib.pyplot as plt
    import seaborn as sns
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
    
    # Plot 1: Speed variance by vehicle type
    if 'vehicle_type' in df.columns:
        sns.boxplot(data=df, x='vehicle_type', y='speed_variance', ax=ax1, hue='vehicle_type', legend=False)
        ax1.set_xlabel('Vehicle Type', fontweight='bold')
        ax1.set_ylabel('Speed Variance', fontweight='bold')
        ax1.set_title('Speed Variance by Vehicle Type', fontweight='bold', pad=15)
        ax1.grid(True, alpha=0.3, linestyle='--')
    
    # Plot 2: Average speed vs variance
    ax2.scatter(df['average_speed'], df['speed_variance'],
               c=df['vehicle_type'].map({'emergency': '#ff7f0e', 'regular': '#1f77b4'}),
               alpha=0.6, s=50, edgecolors='black', linewidth=0.5)
    ax2.set_xlabel('Average Speed (m/s)', fontweight='bold')
    ax2.set_ylabel('Speed Variance', fontweight='bold')
    ax2.set_title('Speed Variance vs Average Speed', fontweight='bold', pad=15)
    ax2.grid(True, alpha=0.3, linestyle='--')
    
    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#ff7f0e', label='Emergency'),
        Patch(facecolor='#1f77b4', label='Regular')
    ]
    ax2.legend(handles=legend_elements, loc='best', framealpha=0.9)
    
    plt.tight_layout()
    
    filepath = Path(plotter.output_directory) / "speed_variance_from_csv.png"
    plt.savefig(filepath, dpi=300, bbox_inches='tight')
    plt.close()
    
    print("✓ Generated speed variance plot from CSV")


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description='Generate plots from PerformanceMonitor CSV files'
    )
    parser.add_argument('--input', '-i', default='results',
                       help='Input directory containing CSV files')
    parser.add_argument('--output', '-o', default='plots',
                       help='Output directory for plots')
    parser.add_argument('--prefix', '-p', default='performance',
                       help='CSV filename prefix')
    
    args = parser.parse_args()
    
    print("=" * 70)
    print("  PLOTTING FROM CSV FILES")
    print("=" * 70)
    print(f"\nInput Directory:  {args.input}")
    print(f"Output Directory: {args.output}")
    print(f"File Prefix:      {args.prefix}")
    
    # Find CSV files
    print("\nSearching for CSV files...")
    csv_files = find_latest_csv_files(args.input, args.prefix)
    
    if not csv_files:
        print(f"\n✗ No CSV files found in {args.input}")
        print(f"  Looking for files matching: {args.prefix}_*_*.csv")
        return
    
    print(f"\nFound {len(csv_files)} CSV file(s):")
    for metric, filepath in csv_files.items():
        print(f"  ✓ {metric}: {Path(filepath).name}")
    
    # Create plotter
    plotter = PerformancePlotter(output_directory=args.output)
    
    # Generate plots
    print("\nGenerating plots...")
    
    if 'latency' in csv_files:
        try:
            plot_latency_from_csv(csv_files['latency'], plotter)
        except Exception as e:
            print(f"✗ Error plotting latency: {e}")
    
    if 'message_success' in csv_files:
        try:
            plot_reliability_from_csv(csv_files['message_success'], plotter)
        except Exception as e:
            print(f"✗ Error plotting reliability: {e}")
    
    if 'ambulance_travel' in csv_files:
        try:
            plot_ambulance_speed_from_csv(csv_files['ambulance_travel'], plotter)
        except Exception as e:
            print(f"✗ Error plotting ambulance speed: {e}")
    
    if 'lane_clearance' in csv_files:
        try:
            plot_lane_clearance_from_csv(csv_files['lane_clearance'], plotter)
        except Exception as e:
            print(f"✗ Error plotting lane clearance: {e}")
    
    if 'speed_variance' in csv_files:
        try:
            plot_speed_variance_from_csv(csv_files['speed_variance'], plotter)
        except Exception as e:
            print(f"✗ Error plotting speed variance: {e}")
    
    print("\n" + "=" * 70)
    print("  PLOTTING COMPLETE")
    print("=" * 70)
    print(f"\nPlots saved to: {args.output}/")
    print("=" * 70)


if __name__ == "__main__":
    main()
